### ISSUE TITLE
Degree requirements

### ISSUE THREAD

**Issue by kate-rydberg** [StanfordCS194/Rabbit-Universe#17]

**Comment by garrickf** [comment]
Kate, opening a new branch to style the sidebar, putting this issue in that branch seems ideal

**Comment by garrickf** [comment]
https://github.com/StanfordCS194/Rabbit-Universe/pull/new/sidebar-deluxe

**Comment by kayleebement** [comment]
completed in satisfy reqs branch, will close when merged
