### ISSUE TITLE
only show classes that are offered in the specific quarter

### ISSUE THREAD

**Issue by kate-rydberg** [StanfordCS194/Rabbit-Universe#32]
We should think about how we want to do this re previous / future years

**Comment by RileyWilson** [comment]
I can start on this once master is updated with the redux stuff and ready to be freshly branched, will also add a couple more depts' courses to the database.

**Comment by kayleebement** [comment]
past - no validation
present - validation
future - warning

**Comment by kayleebement** [comment]
future - also have a checkbox to toggle only showing classes that are offered that quarter in the current year

**Comment by kayleebement** [comment]
after discussion - changed it so that we don't actually need to know their current year, just always have the option to filter class choices by what's offered current year, and warn them if they try addding something that's not offered that quarter in this year

**Comment by garrickf** [comment]
Closed by #98
