### ISSUE TITLE
create info modal + show more information about course

### ISSUE THREAD

**Issue by kayleebement** [StanfordCS194/Rabbit-Universe#35]

**Comment by eliew88** [comment]
I am working on the info modal but not yet anything about showing course info.

**Comment by garrickf** [comment]
@eliew88 and @kayleebement, is this the info modal for a requirement or a course? I just started an info modal branch, but it's for the requirements, i.e. the design

<img width="218" alt="Screen Shot 2019-05-23 at 2 14 02 AM" src="https://user-images.githubusercontent.com/20538779/58767559-ccfcd180-8541-11e9-9b1f-d82c47b3e3a2.png">

**Comment by kayleebement** [comment]
for the course, sorry I didn't see this earlier!

**Comment by kayleebement** [comment]
I'll start working on the course one

**Comment by garrickf** [comment]
I have a branch starting this, let me integrate master and we can both develop on it @kayleebement!
