### ISSUE TITLE
See courses that are satisfying each requirement in sidebar

### ISSUE THREAD

**Issue by kayleebement** [StanfordCS194/Rabbit-Universe#62]
assigning garrick bc needs to be designed

**Comment by garrickf** [comment]
<img width="218" alt="Screen Shot 2019-05-23 at 2 14 02 AM" src="https://user-images.githubusercontent.com/20538779/58499497-28d7ec80-8135-11e9-868b-f251e4ee577c.png">
<img width="784" alt="Screen Shot 2019-05-23 at 2 13 53 AM" src="https://user-images.githubusercontent.com/20538779/58499498-28d7ec80-8135-11e9-88db-d6031cf33274.png">
<img width="788" alt="Screen Shot 2019-05-23 at 2 13 47 AM" src="https://user-images.githubusercontent.com/20538779/58499499-28d7ec80-8135-11e9-985d-74d8a8bd4444.png">
