### ISSUE TITLE
Add "tracks" to degree schema + degree modal

### ISSUE THREAD

**Issue by kayleebement** [StanfordCS194/Rabbit-Universe#64]

**Comment by kate-rydberg** [comment]
I'm planning on working on this with @kayleebement this week

**Comment by kayleebement** [comment]
@kate-rydberg - gonna make a branch for this and set up the schema / database end

**Comment by kayleebement** [comment]
@kate-rydberg database and schema are ready! lmk if you want any more help w this branch :)

**Comment by garrickf** [comment]
Resolved by #81
